# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

image: python:3.10-bullseye

variables:
  WM_PROJECT_DIR: "/usr/share/openfoam"
  OMPI_ALLOW_RUN_AS_ROOT: "1"
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: "1"

stages:
  - test
  - publish

# sast:
#   stage: test
# include:
# - template: Security/SAST.gitlab-ci.yml

cache:
  # Required to keep artifacts from old builds, e.g. from default
  paths:
    - public
    - .apt
    - .venv

before_script:
  - rm -f /etc/apt/apt.conf.d/docker-clean
  - mkdir .apt && mkdir /var/cache/apt/archives && mount --bind .apt /var/cache/apt/archives/
  - apt-get update && apt-get install -y rsync openfoam libgl1 xvfb libgl1-mesa-dev
  - pip install poetry
  - poetry config virtualenvs.in-project true
  # see https://github.com/pydata/pydata-sphinx-theme/issues/1253
  - poetry config installer.modern-installation false
  - poetry install --without dev -E pyvista

pytest:
  stage: test
  script:
    - poetry run pytest tests doc/examples --cov --cov-report term --cov-report xml
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

pages:
  stage: publish
  script:
    - poetry run xvfb-run --auto-servernum sphinx-build -W -b html -d doc/_build/doctrees doc doc/_build/html
    - mkdir -p public/$CI_COMMIT_REF_NAME
    - rsync -rvc --delete doc/_build/html/* public/$CI_COMMIT_REF_NAME/
    # This directory can become too large leading to error.
    # It can be purged with the botton "Clear runner caches"
    # in https://foss.heptapod.net/fluiddyn/fluidsimfoam/-/pipelines
    - ls public
    - echo "CI_COMMIT_REF_NAME="$CI_COMMIT_REF_NAME
    - echo See https://fluiddyn.pages.heptapod.net/fluidsimfoam/$CI_COMMIT_REF_NAME
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - public
    expire_in: 5 days
  when: always