# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

image: python:3.10-bullseye

stages:
  - test
  - publish

# sast:
#   stage: test
# include:
# - template: Security/SAST.gitlab-ci.yml

cache:
  # Required to keep artifacts from old builds, e.g. from default
  paths:
    - public

pytest:
  stage: test
  script:
    - pip install poetry
    # see https://github.com/pydata/pydata-sphinx-theme/issues/1253
    - poetry config installer.modern-installation false
    - poetry install --without dev
    - poetry run pytest tests doc/examples

pages:
  stage: publish
  script:
    - apt-get update && apt-get install -y rsync
    - pip install poetry
    # see https://github.com/pydata/pydata-sphinx-theme/issues/1253
    - poetry config installer.modern-installation false
    - poetry install --without dev
    - poetry run sphinx-build -b html -d doc/_build/doctrees doc doc/_build/html
    - mkdir -p public/$CI_COMMIT_REF_NAME
    - rsync -rvc --delete doc/_build/html/* public/$CI_COMMIT_REF_NAME/
    - ls public
    - echo "CI_COMMIT_REF_NAME="$CI_COMMIT_REF_NAME
    - echo See https://fluiddyn.pages.heptapod.net/fluidsimfoam/$CI_COMMIT_REF_NAME
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - public
    expire_in: 5 days
  when: always