version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - openfoam
    - libgl1
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
      # see https://github.com/pydata/pydata-sphinx-theme/issues/1253
      - poetry config installer.modern-installation false
    post_install:
      - poetry install --with doc

sphinx:
  configuration: doc/conf.py
