version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - openfoam
  jobs:
    post_create_environment:
      - pip install pdm
    post_install:
      - pdm install -G pyvista
      - pdm run pip uninstall vtk -y
      - pdm run pip install vtk-osmesa --extra-index-url https://gitlab.kitware.com/api/v4/projects/13/packages/pypi/simple

sphinx:
  configuration: doc/conf.py
